name: tests-payments

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo $SECRET_TEST && cd payments && npm install && npm run test:ci
        env:
          STRIPE_KEY: ${{ secrets.STRIPE_KEY }}
          SECRET_TEST: ${{ secrets.SECRET_TEST }}
